name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.build.outputs.version }}

    strategy:
      matrix:
        version:
          - 17

    steps:
      - id: checkout
        uses: actions/checkout@v3

      - id: build
        uses: kkorolyov/publish-gradle@0.4.0
        with:
          java-version: ${{ matrix.version }}
          publish-branch: master
          # just tag to publish per-platform downstream
          publish-task: ""
          token: ${{ secrets.GITHUB_TOKEN }}

  package:
    runs-on: ${{ matrix.os }}
    needs: build
    if: ${{ needs.build.outputs.version != 0 }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        version:
          - 17

    steps:
      - id: checkout
        uses: actions/checkout@v3
      - id: java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: temurin
          cache: gradle

      - id: package
        run: ./gradlew jpackage "-Pjpackage.version=${{ needs.build.outputs.version }}" --no-daemon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: upload
        uses: actions/upload-artifact@v2
        with:
          name: pkg-${{ matrix.os }}-jdk${{ matrix.version }}
          path: "build/jpackage/*.*"

  release:
    runs-on: ubuntu-latest
    needs:
      - build
      - package

    steps:
      - id: download
        uses: actions/download-artifact@v2

      - id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.build.outputs.version }}
          generate_release_notes: true
          files: "**/*.*"
