name: publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [ 17 ]

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.version }}
          cache: gradle
          distribution: zulu

      - name: tag
        run: ./gradlew reckonTagPush --no-daemon -Preckon.stage=final
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
