name: publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]
        version: [ 17 ]

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: publish
        uses: kkorolyov/publish-gradle@0.2.0
        with:
          java-version: ${{ matrix.version }}
          package-task: githubRelease
          token: ${{ secrets.GITHUB_TOKEN }}
